### ISSUE TITLE
Не совместимо с php7.2

### ISSUE THREAD

**Issue by sukhikh18** [yamilovs/SypexGeo#3]
Как и решение от zapimir и BINOVATOR не хочет работать на версиях 7.0 - 7.3 (какие то проблемы с кодировкой)

**Comment by yamilovs** [comment]
Можете предоставить более точные данные об ошибке, желательно весь `stack trace`? Мои коллеги используют для работы PHP 7.3 - вопросов не возникало. Так же есть тесты для работы с файловой системой для всех версий PHP выше 7.0.
Спасибо.

**Comment by yamilovs** [comment]
Closed due to inactivity
